{ pkgs, ... }:

let
  # Generated by scripts/detect-hw.sh; an empty string means no NVIDIA GPU.
  hasNvidia = (import ../core/gpu/detected.nix).nvidia != "";
in
{
  imports = [
    ./clipman.nix
    ./nautilus.nix
  ];

  home.packages = with pkgs; [
    grim
    slurp
    wl-clipboard
    libnotify
    sway-contrib.grimshot
    swappy
    swaybg
    networkmanagerapplet
    blueman
    clipman
    fuzzel
    kdePackages.breeze-icons
    kdePackages.qtwayland
    samba
    cifs-utils
    foot
    brightnessctl
    playerctl
    wireplumber
    xwayland-satellite
    xrandr
    socat
    jq
    nixly_launcher
  ];
  # mcontrolcenter is installed system-wide in modules/system/msi-ec.nix; the GUI
  # autostarts from config.kdl below, the only mechanism that works here.

  home.file."Pictures/wallpapers/beach.jpg".source = ../../wallpapers/beach.jpg;

  xdg.configFile."nixlytile/config.kdl".text = ''
    // nixlytile config (managed by home-manager: modules/user/nixlytile.nix)
    // Loaded at startup: $XDG_CONFIG_HOME/nixlytile/config.kdl
    // Hot-reload: pkill -USR1 nixlytile

    appearance {
        gaps 4
        border-px 1
        smartgaps           false
        sloppy-focus        true
        bypass-surface-visibility false
        gaps-enabled        true
        root-color          "#222222ff"
        border-color        "#595959ff"
        focus-color         "#00beffff"
        urgent-color        "#ff0000ff"
        fullscreen-bg       "#1a1a1aff"
        resize-factor       0.0002
        resize-interval-ms  8
        resize-min-pixels   1.0
        resize-ratio-epsilon 0.001
        lock-cursor         false
    }

    input {
        keyboard {
            layout       "no"
            repeat-delay 300
            repeat-rate  100
        }
        touchpad {
            tap                     true
            tap-and-drag            true
            drag-lock               true
            natural-scroll          true
            disable-while-typing    true
            left-handed             false
            middle-button-emulation false
            scroll-method   "2fg"
            click-method    "button-areas"
            send-events     "enabled"
            accel-profile   "adaptive"
            accel-speed     0.0
            button-map      "lrm"
        }
    }

    // Unreal Editor deler app-id mellom prosjektvelgeren og selve editoren,
    // saa reglene skiller paa tittel.  Velger- og opprett-vinduene er dialoger
    // som ikke hoerer hjemme flislagt over hele skjermen; editoren selv
    // (tittel "<Prosjekt> - Unreal Editor") skal fortsatt flislegges.
    window-rule {
        app-id   "UnrealEditor"
        title    "Unreal Engine 5"
        floating true
    }
    window-rule {
        app-id   "UnrealEditor"
        title    "New Project"
        floating true
    }
    window-rule {
        app-id   "UnrealEditor"
        title    "Create Project"
        floating true
    }

    // Citrix Workspace: sesjonsvinduet fyller skjermen naar sesjonsopploesningen
    // matcher monitoren, og skal ikke faa game-behandling eller lov til aa
    // fullskjerme seg selv.
    window-rule {
        app-id     "Wfica"
        game       false
        fullscreen false
    }

    modkey      "Super"
    monitorkey  "Ctrl"

    // Multi-monitor gaming: oppløsningen spillet velger avgjør.
    // Normal oppløsning (≤ skjermen) = 1 skjerm som før. Velger spillet
    // en surround-oppløsning som er bredere/høyere enn skjermen (f.eks.
    // 5760x1080 på 3x1080p) spennes det automatisk over alle aktive
    // skjermer, og musen kan bevege seg over hele flaten.
    // Super+Shift+M tvinger span på for spill som ikke kan be om større
    // oppløsning selv (trykk igjen for å gå tilbake til auto).
    // "off" = aldri automatisk span.
    game-span "auto"

    ${pkgs.lib.optionalString hasNvidia ''
    // Late-latch (utsett game-commit til rett foer vblank) er av paa
    // NVIDIA: driveren avviser IN_FENCE_FD (EPERM) paa 555+, saa
    // wlroots-workarounden venter ut fencen CPU-side INNE i commiten.
    // Latch-budsjettet (maks 10 ms) dekker ikke en vent som varer til
    // spillets GPU-arbeid er ferdig — commiten bommer paa vblank og
    // hvert spill jitrer konstant. Immediate-path gir fencen nesten en
    // hel refresh aa signalere paa i stedet.
    game-late-latch false
    ''}
    wallpaper "~/.nixlyos/wallpapers/beach.jpg"

    // "info" i produksjon — debug betyr per-event formatering + logg-IO
    // i frame-pathen.  Sett "debug" midlertidig ved feilsøking.
    log-level "info"

    // Autostart — one process per entry.
    // thunar --daemon fjernet: Nautilus er filbehandleren (Super+e), og
    // thunar-daemonen dro med seg 5 residente gvfs-volume-monitors
    // (goa/gphoto2/afc/mtp/udisks) ved hver innlogging. Thunar starter
    // fortsatt on-demand om noe kaller den.
    autostart "swaybg -i \"$HOME/.nixlyos/wallpapers/beach.jpg\" -m fill"
    autostart "nm-applet --indicator"
    autostart "blueman-applet"
    autostart "xwayland-satellite"
    // Uten RandR-primary regner Wine/UE4 første monitor (HDMI, 1080p) som
    // primær display-enhet, så exclusive fullscreen bare tilbyr 1080p-moduser.
    // Retry-løkke fordi Xwayland-satellite trenger et par sekunder på å komme opp.
    autostart "sh -c 'for i in 1 2 3 4 5 6 7 8 9 10; do DISPLAY=:0 xrandr --output DP-1 --primary 2>/dev/null && break; sleep 1; done'"
    autostart "sh -c 'wl-paste --type text --watch clipman store --no-persist'"
    autostart "sh -c 'wl-paste --primary --type text --watch clipman store --no-persist'"
    // Prewarm av spill naar maskinen staar urort: 5 min uten input starter
    // nixly-prewarm-games (varmer launch-kjede + alle installerte spill,
    // se prewarm.nix); foerste input etterpaa stopper den momentant.
    // Spillstart krever input, saa resume-stoppen treffer alltid foer et
    // spill er oppe — i tillegg nekter service-gaten aa kjoere naar
    // gametune/gamemoded melder aktivt spill.
    // Shader-replay (nixly-prewarm) startes ogsaa ved idle og stoppes paa
    // samme resume: scriptet pauser fossilize naar et SPILL kjoerer, men
    // ikke naar du bare bruker skrivebordet. Flock + stampfiler gjoer at
    // et avbrutt pass er billig aa ta om igjen.
    autostart "sh -c 'exec swayidle -w timeout 300 \"systemctl --user start nixly-prewarm-games.service nixly-prewarm.service\" resume \"systemctl --user stop nixly-prewarm-games.service nixly-prewarm.service\"'"
    // appd walker HELE $HOME ved oppstart (fileindex + gitscan) og bygger
    // et ikon-indeks paa ~21k entries. Rett etter innlogging konkurrerer
    // det med kompositoren om CPU og disk, og musen fryser 2-3s. Utsatt
    // 8s (kompositor + Wayland-klienter er oppe da) og nice 19 saa
    // indekseringen aldri preempter frame-pathen. Super+p virker fra ~8s.
    autostart "sh -c 'sleep 8; exec nice -n 19 appd'"
    // Steam forvarmes i tray etter innlogging: klienten + steamwebhelper
    // er da allerede oppe og shader-cache/VDF-er ligger i page cache, saa
    // "Play" gaar rett i spillstart i stedet for 15-20s klientoppstart.
    // 20s utsettelse + nice 10 saa innloggingen aldri konkurrerer om CPU/IO.
    autostart "sh -c 'sleep 20; exec nice -n 10 steam -silent'"
    autostart "mcontrolcenter"

    // ───────── keybindings ─────────
    // Applications
    bind "Super+Return"       "spawn" "alacritty"
    bind "Super+Shift+Return" "spawn" "alacritty -e bash"
    bind "Super+p"            "spawn" "apptoggle"
    bind "Super+g"            "spawn" "fuzzel"
    bind "Super+i"            "spawn" "fuzzel"
    bind "Super+e"            "spawn" "nautilus --new-window"
    bind "Super+Escape"       "spawn" "nixly-lockscreen"
    bind "Super+F12"          "spawn" "nixly-lockscreen"
    // NIXOS_OZONE_WL=1 (modules/system/nixlytile.nix) gir Wayland uten flagg.
    bind "Super+BackSpace"    "spawn" "google-chrome-stable"
    bind "Super+s"            "spawn" "grimshot copy area"
    bind "Print"            "spawn" "grimshot copy area"
    bind "Shift+Print"      "spawn" "grimshot copy output"

    // Window management
    bind "Super+q"            "killclient"
    bind "Super+Shift+Q"      "quit"
    bind "Super+Shift+space"  "togglefloating"
    bind "Super+c"            "togglefloating"
    bind "Super+f"            "maximize-column"
    bind "Super+Shift+F"      "togglefullscreen"
    bind "Super+Shift+M"      "togglegamespan"
    bind "Super+b"            "togglestatusbar"

    // Focus navigation
    bind "Super+h"            "focus-column-dir"             -1
    bind "Super+l"            "focus-column-dir"             1
    bind "Super+Left"         "focus-column-dir"             -1
    bind "Super+Right"        "focus-column-dir"             1
    bind "Super+j"            "focus-window-in-column-dir"   1
    bind "Super+k"            "focus-window-in-column-dir"   -1
    bind "Super+Up"           "focus-workspace-dir"          -1
    bind "Super+Down"         "focus-workspace-dir"          1

    // Window movement
    bind "Super+Shift+H"      "move-column-dir"              -1
    bind "Super+Shift+L"      "move-column-dir"              1
    bind "Super+Shift+J"      "move-window-in-column-dir"    1
    bind "Super+Shift+K"      "move-window-in-column-dir"    -1
    bind "Super+Shift+Left"   "move-column-dir"              -1
    bind "Super+Shift+Right"  "move-column-dir"              1
    bind "Super+Shift+Up"     "move-window-in-column-dir"    -1
    bind "Super+Shift+Down"   "move-window-in-column-dir"    1

    // Alt-direction: move tile within current workspace
    bind "Alt+h"            "move-column-dir"              -1
    bind "Alt+l"            "move-column-dir"              1
    bind "Alt+Left"         "move-column-dir"              -1
    bind "Alt+Right"        "move-column-dir"              1
    bind "Alt+k"            "move-window-in-column-dir"    -1
    bind "Alt+j"            "move-window-in-column-dir"    1

    // Column width / consume / expel
    bind "Super+r"            "switch-preset-column-width"
    bind "Super+a"            "swap-window-dir"              -1
    bind "Super+d"            "swap-window-dir"              1
    bind "Super+x"            "expel-window-from-column"
    bind "Super+Ctrl+Left"    "switch-preset-column-width"
    bind "Super+Ctrl+Right"   "switch-preset-column-width"
    bind "Super+Ctrl+Up"      "center-column"
    bind "Super+Ctrl+Down"    "maximize-column"

    // Workspaces 1..9
    bind "Super+1" "focus-workspace-n" 0
    bind "Super+2" "focus-workspace-n" 1
    bind "Super+3" "focus-workspace-n" 2
    bind "Super+4" "focus-workspace-n" 3
    bind "Super+5" "focus-workspace-n" 4
    bind "Super+6" "focus-workspace-n" 5
    bind "Super+7" "focus-workspace-n" 6
    bind "Super+8" "focus-workspace-n" 7
    bind "Super+9" "focus-workspace-n" 8
    bind "Super+0" "focus-workspace-n" 9
    bind "Super+Shift+1" "move-client-to-ws-n" 0
    bind "Super+Shift+2" "move-client-to-ws-n" 1
    bind "Super+Shift+3" "move-client-to-ws-n" 2
    bind "Super+Shift+4" "move-client-to-ws-n" 3
    bind "Super+Shift+5" "move-client-to-ws-n" 4
    bind "Super+Shift+6" "move-client-to-ws-n" 5
    bind "Super+Shift+7" "move-client-to-ws-n" 6
    bind "Super+Shift+8" "move-client-to-ws-n" 7
    bind "Super+Shift+9" "move-client-to-ws-n" 8
    bind "Super+Shift+0" "move-client-to-ws-n" 9
    bind "Super+Tab"     "focus-last-workspace"

    // Multi-monitor
    bind "Super+comma"           "focusmon"        "left"
    bind "Super+period"          "focusmon"        "right"
    bind "Super+Shift+less"      "tagmon"          "left"
    bind "Super+Shift+greater"   "tagmon"          "right"
    bind "MonitorMod+Up"       "warptomonitor"   "up"
    bind "MonitorMod+Down"     "warptomonitor"   "down"
    bind "MonitorMod+Left"     "warptomonitor"   "left"
    bind "MonitorMod+Right"    "warptomonitor"   "right"
    bind "MonitorMod+Shift+exclam"     "tagtomonitornum" 0
    bind "MonitorMod+Shift+at"         "tagtomonitornum" 1
    bind "MonitorMod+Shift+numbersign" "tagtomonitornum" 2
    bind "MonitorMod+Shift+dollar"     "tagtomonitornum" 3

    // VT switch (Ctrl+Alt+F1..F12)
    bind "Ctrl+Alt+XF86Switch_VT_1"  "chvt" 1
    bind "Ctrl+Alt+XF86Switch_VT_2"  "chvt" 2
    bind "Ctrl+Alt+XF86Switch_VT_3"  "chvt" 3
    bind "Ctrl+Alt+XF86Switch_VT_4"  "chvt" 4
    bind "Ctrl+Alt+XF86Switch_VT_5"  "chvt" 5
    bind "Ctrl+Alt+XF86Switch_VT_6"  "chvt" 6
    bind "Ctrl+Alt+XF86Switch_VT_7"  "chvt" 7
    bind "Ctrl+Alt+XF86Switch_VT_8"  "chvt" 8
    bind "Ctrl+Alt+XF86Switch_VT_9"  "chvt" 9
    bind "Ctrl+Alt+XF86Switch_VT_10" "chvt" 10
    bind "Ctrl+Alt+XF86Switch_VT_11" "chvt" 11
    bind "Ctrl+Alt+XF86Switch_VT_12" "chvt" 12
    bind "Ctrl+Alt+Terminate_Server" "quit"
  '';
}
