{ ... }:

{
  imports = [
    ./input.nix
    ./distro.nix
    ./boot.nix
    ../system/SDDM.nix
    ./networking.nix
    ./tailscale.nix
    ./ssh_gate.nix
    ./autoupdate.nix
    ./nix.nix
    ./nfs.nix
    ./ssh.nix
    ./gaming.nix
    ./gametune.nix
    ./packages.nix
    ./totalvim.nix
    ./users.nix
    ./timezone_locale.nix
    ./system_services.nix
    ./docs.nix
    ./perf.nix
    ./prewarm.nix
    ./overhead.nix
    ./wayland.nix
    ./sound.nix
    ./zram.nix
    ./security.nix
    ./power.nix
    # scripts/detect-hw.sh rewrites the cpu/ and gpu/ imports below this anchor
    # before every eval, so none of them are committed here.
    # <detect-hw: cpu + gpu>
    ./cpu/intel.nix
    ./gpu/nvidia_only.nix
    ../system/nixlytile.nix
    ./newsboat.nix
    ./w3m.nix
    ./mpv.nix
    ./retroarch.nix
    ./drawingtablet.nix
    ./citrix.nix
    ./dcspit.nix
    ../system/htpc.nix
    ../system/idle.nix
    # Generated by scripts/detect-hw.sh: model-specific modules and the services
    # that only run when the device is actually present.
    ./hw/profile.nix
    ./hw/devices.nix
    ../services/on-demand
  ];
}
